/***********************************************************************
 *
 * File Name : backend.Jenkinsfile
 *
 * Purpose:
 * --------
 * Build the Backend Docker Image
 * Push the Backend Docker Image to Docker Hub
 *
 * Pipeline Flow
 * -------------
 *
 * GitHub
 *    │
 * Checkout Source Code
 *    │
 * Build Docker Image
 *    │
 * Login to Docker Hub
 *    │
 * Push Docker Image
 *    │
 * Cleanup Local Images
 *
 ***********************************************************************/

pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec: 
  containers:
  - name: docker
    image: docker:24.0.5
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock

  - name: jnlp
    image: jenkins/inbound-agent:latest

  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }
    
    environment {
        // Change this to your frontend image name
        DOCKER_IMAGE = "navin1199/backend"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/Navin470/employee-crud-app'
            }
        }

        stage('Build Backend Image') {
            steps {
                container("docker"){
                    sh """
                        # Point this to the folder where your Backend Dockerfile is
                        docker build -t $DOCKER_IMAGE:$DOCKER_TAG Backend
                    """
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                container("docker"){
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'USERNAME',
                        passwordVariable: 'PASSWORD'
                    )]) {
                        sh "echo \$PASSWORD | docker login -u \$USERNAME --password-stdin"
                    }
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                container("docker"){
                    sh "docker push $DOCKER_IMAGE:$DOCKER_TAG"
                }
            }
        }

        stage('Cleanup') {
            steps {
                container("docker"){
                    sh "docker rmi $DOCKER_IMAGE:$DOCKER_TAG || true"
                }
            }
        }
    }

    post {
        success {
            echo "Backend Service Build & Push Successful"
        }
        failure {
            echo "Backend Build Failed"
        }
    }
}