/***********************************************************************
 *
 * File Name  : backend.Jenkinsfile
 *
 * Purpose:
 * ----------
 * Build Backend Docker Image
 * Push Backend Docker Image to Docker Hub
 *
 * Author : Navin Raj
 *
 ***********************************************************************/

pipeline {

    /*******************************************************************
     * Jenkins Kubernetes Agent
     *******************************************************************/
    agent {
        kubernetes {

            yaml '''
apiVersion: v1
kind: Pod

metadata:
  labels:
    component: backend-ci

spec:

  containers:

  - name: docker
    image: docker:24.0.5

    command:
    - cat

    tty: true

    volumeMounts:

    - name: dockersock
      mountPath: /var/run/docker.sock

  - name: jnlp
    image: jenkins/inbound-agent:latest

  volumes:

  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
'''
        }
    }

    /*******************************************************************
     * Environment Variables
     *******************************************************************/
    environment {

        DOCKER_IMAGE = "navin1199/employee-backend"

        DOCKER_TAG = "${BUILD_NUMBER}"

    }

    stages {

        /***************************************************************
         * Checkout Source Code
         ***************************************************************/
        stage('Checkout Source Code') {

            steps {

                git branch: 'master',
                    url: 'https://github.com/Navin470/employee-crud-app.git'

            }

        }

        /***************************************************************
         * Build Backend Image
         ***************************************************************/
        stage('Build Backend Docker Image') {

            steps {

                container('docker') {

                    sh """

                        echo "Building Backend Docker Image..."

                        docker build \
                        -t ${DOCKER_IMAGE}:${DOCKER_TAG} \
                        backend

                    """

                }

            }

        }

        /***************************************************************
         * Login Docker Hub
         ***************************************************************/
        stage('Docker Hub Login') {

            steps {

                container('docker') {

                    withCredentials([

                        usernamePassword(

                            credentialsId: 'dockerhub-creds',

                            usernameVariable: 'USERNAME',

                            passwordVariable: 'PASSWORD'

                        )

                    ]) {

                        sh """

                        echo \$PASSWORD | docker login \
                        -u \$USERNAME \
                        --password-stdin

                        """

                    }

                }

            }

        }

        /***************************************************************
         * Push Docker Image
         ***************************************************************/
        stage('Push Backend Docker Image') {

            steps {

                container('docker') {

                    sh """

                        docker push ${DOCKER_IMAGE}:${DOCKER_TAG}

                    """

                }

            }

        }

        /***************************************************************
         * Cleanup Local Image
         ***************************************************************/
        stage('Cleanup') {

            steps {

                container('docker') {

                    sh """

                    docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG} || true

                    """

                }

            }

        }

    }

    /*******************************************************************
     * Pipeline Status
     *******************************************************************/
    post {

        success {

            echo "========================================="

            echo "Backend Image Successfully Pushed"

            echo "Image : ${DOCKER_IMAGE}:${DOCKER_TAG}"

            echo "========================================="

        }

        failure {

            echo "Backend Pipeline Failed"

        }

        always {

            cleanWs()

        }

    }

}