apiVersion: v1

kind: Secret

metadata:

  name: mysql-secret

  namespace: employee-app

type: Opaque

stringData:

  DB_USER: root

  DB_PASSWORD: root

  MYSQL_ROOT_PASSWORD: root

# Notice we use

# stringData

# instead of Base64.